
import Home from './components/home/home';
//components
import Header from './components/headers/headers';
import { Box } from '@mui/material';

function App() {
  return (
    <div >
      <Header/>            
      <Box style={{marginTop : 54 }}> 
                                                                       
     <Home/>
      </Box>
    </div>
  );
}

export default App;

// line 11 marginTop so that the row of under nav bar generated by <home> component
// does hide under the navbar as navbar has by default has position fixed